  name: First
on: 
  push:
jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: franclarke/DocumentatorAction@main
      env:
        GITHUB_TOKEN: ${{ secrets.OPENAI_API_KEY }}