name: First
on:
  push:
    branches: [main] # Ejecuta la acción solo en la rama "main"
jobs:
  job1:
    name: "Mi primer job"
    runs-on: windows-latest
    steps:
      - name: "Descargar código fuente"
        uses: actions/checkout@v2
      - name: "Ejecutar programa Python con parámetros EATI y 2023"
        run: python eati.py "EATI" "2023"
  job2:
    name: "Mi segundo job"
    runs-on: windows-latest
    steps:
      - name: "Descargar código fuente"
        uses: actions/checkout@v2
      - name: "Ejecutar programa Python con parámetros de texto"
        run: python eati.py "Mi nombre es Francisco\n" "Estoy haciendo un curso de GitHub Actions"
