name: Fourth
on:
  push:
    branches: ["workflow4"]
env:
  WORKFLOW_VARIABLE: 'variable WORKFLOW_VARIABLE'
  SCOPE: 'variable SCOPE'
jobs:
  job1:
    name: "Trabajo 1"
    runs-on: ubuntu-latest
    env:
      JOB_VARIABLE: "asd"
      SCOPE: 'Primer nuevo valor de scope'
    steps:
      - name: "Primer step"
        env:
          STEP_VARIABLE: "asd"
          SCOPE: 'Segundo nuevo valor de scope'
        run: |
            echo $WORKFLOW_VARIABLE
            echo $JOB_VARIABLE
            echo $STEP_VARIABLE
            echo $SCOPE
      - name: "Segundo step"
        run: echo $SCOPE
  job2:
    name: "Trabajo 2"
    runs-on: ubuntu-latest
    steps:
      - run: echo $SCOPE