name: Sixth
on: 
  push:
    branches: [ "workflow6" ]
env:
  FILE_NAME: output.txt
jobs:
  build:
    name: "build"
    runs-on: ubuntu-20.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          repository: jmoyano/cautious-meme
          ref: main
      - name: compilar main
        run: gcc main.c -o main
      - name: upload articfact
        uses: actions/upload-artifact@v3
        with:
          name: main
          path: ./main
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: main
    - name: Verify downloaded file
      run: ls
    - name: Run test
      run: |
          chmod +x main
          declare -i output = $(./main)
          if ["$output" -eq 0]; then
            echo "Exito"
          else
            echo "Error"
          fi